const { sendMail } = require('../utils/emailService');
const logger = require('../utils/logger');

const emailReport = async (req, res) => {
  try {
    const { to, subject, reportName, reportData, htmlContent } = req.body;

    if (!to || !reportName) {
      return res.status(400).json({ error: 'Recipient email and report name are required' });
    }

    const defaultHtml = `
      <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #eee; border-radius: 5px;">
        <h2 style="color: #1e40af;">${reportName}</h2>
        <p>Hello,</p>
        <p>Please find the requested report below.</p>
        <div style="margin-top: 20px; padding: 15px; background-color: #f8fafc; border-radius: 5px;">
          ${htmlContent || '<p>Report details are attached or included in this data stream.</p>'}
        </div>
        <p style="margin-top: 20px;">Generated by DIMA ERP System.</p>
        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
        <p style="font-size: 12px; color: #777;">Date: ${new Date().toLocaleString()}</p>
      </div>
    `;

    const success = await sendMail({
      to,
      subject: subject || `[ERP REPORT] ${reportName}`,
      html: defaultHtml,
      referenceType: 'REPORT',
    });

    if (success) {
      res.json({ message: 'Report emailed successfully' });
    } else {
      res.status(500).json({ error: 'Failed to send email. Check SMTP configuration.' });
    }
  } catch (err) {
    logger.error('emailReport error:', err.message);
    res.status(500).json({ error: 'An error occurred while emailing the report' });
  }
};

module.exports = { emailReport };
